import { COLLECTIONS_ENUM, SETTINGS_ENUM } from '@src/lib/enums/collections';
import { DB } from '@src/settings/firebase';
import { collection, doc } from 'firebase/firestore';

export const COLLECTIONS = {
  IMPORT_CALCULATIONS: collection(DB, COLLECTIONS_ENUM.IMPORT_CALCULATIONS),
  USERS: collection(DB, COLLECTIONS_ENUM.USERS),
  APPLICATION_SETTINGS: collection(DB, COLLECTIONS_ENUM.APPLICATION_SETTINGS),
  DAY_BOOK_TRANSACTIONS: collection(DB, COLLECTIONS_ENUM.DAY_BOOK_TRANSACTIONS),
  CLIENTS: collection(DB, COLLECTIONS_ENUM.CLIENTS),
  PROJECTS: collection(DB, COLLECTIONS_ENUM.PROJECTS),
  EXPENSES: collection(DB, COLLECTIONS_ENUM.EXPENSES),
  RECEIVED_INVOICES: collection(DB, COLLECTIONS_ENUM.RECEIVED_INVOICES),
  CUSTOMS_PAYMENTS: collection(DB, COLLECTIONS_ENUM.CUSTOMS_PAYMENTS),
  NON_DEDUCTIBLES: collection(DB, COLLECTIONS_ENUM.NON_DEDUCTIBLES),
  SALE_NOTES: collection(DB, COLLECTIONS_ENUM.SALE_NOTES),
  DOUBLE_ENTRY_ACCOUNTING: collection(
    DB,
    COLLECTIONS_ENUM.DOUBLE_ENTRY_ACCOUNTING
  ),
  PAYMENTS: collection(DB, COLLECTIONS_ENUM.PAYMENTS),
};

export const APPLICATION_SETTINGS = {
  ACCOUNT_CATEGORIES: doc(
    COLLECTIONS.APPLICATION_SETTINGS,
    SETTINGS_ENUM.ACCOUNT_CATEGORIES
  ),
};
