import { CalculateImportationResult } from '@src/types/importCalculator';

export const _expectedEmptySingleItemImportation: CalculateImportationResult = {
  pricesArray: [0],
  articlesReport: [
    {
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      ISD: 0,
      margin: 0,
      name: 'mocked-item',
      quantity: 1,
      rowWeight: 0,
      tariff: 0,
      tariffRate: 0,
      unitCost: 0,
      unitImportCost: 0,
      unitItemProfit: 0,
      unitLocalFleetCost: 0,
      unitOriginCosts: 0,
      unitPrice: 0,
      unitTaxesFee: 0,
      unitWeight: 0,
      weightFraction: 0,
    },
  ],
};

export const _expectedEmptyMultiItemImportation: CalculateImportationResult = {
  pricesArray: [0, 0, 0, 0],
  articlesReport: [
    {
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      ISD: 0,
      margin: 0,
      name: 'mocked-item-1',
      quantity: 1,
      rowWeight: 0,
      tariff: 0,
      tariffRate: 0,
      unitCost: 0,
      unitImportCost: 0,
      unitItemProfit: 0,
      unitLocalFleetCost: 0,
      unitOriginCosts: 0,
      unitPrice: 0,
      unitTaxesFee: 0,
      unitWeight: 0,
      weightFraction: 0,
    },
    {
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      ISD: 0,
      margin: 0,
      name: 'mocked-item-2',
      quantity: 1,
      rowWeight: 0,
      tariff: 0,
      tariffRate: 0,
      unitCost: 0,
      unitImportCost: 0,
      unitItemProfit: 0,
      unitLocalFleetCost: 0,
      unitOriginCosts: 0,
      unitPrice: 0,
      unitTaxesFee: 0,
      unitWeight: 0,
      weightFraction: 0,
    },
    {
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      ISD: 0,
      margin: 0,
      name: 'mocked-item-3',
      quantity: 1,
      rowWeight: 0,
      tariff: 0,
      tariffRate: 0,
      unitCost: 0,
      unitImportCost: 0,
      unitItemProfit: 0,
      unitLocalFleetCost: 0,
      unitOriginCosts: 0,
      unitPrice: 0,
      unitTaxesFee: 0,
      unitWeight: 0,
      weightFraction: 0,
    },
    {
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      ISD: 0,
      margin: 0,
      name: 'mocked-item-4',
      quantity: 1,
      rowWeight: 0,
      tariff: 0,
      tariffRate: 0,
      unitCost: 0,
      unitImportCost: 0,
      unitItemProfit: 0,
      unitLocalFleetCost: 0,
      unitOriginCosts: 0,
      unitPrice: 0,
      unitTaxesFee: 0,
      unitWeight: 0,
      weightFraction: 0,
    },
  ],
};

export const _expectedSingleItemImportation: CalculateImportationResult = {
  pricesArray: [1213.18],
  articlesReport: [
    {
      CIF: 678.82,
      EXW: 567.1,
      FOB: 612.1,
      FODINFA: 3.39,
      ISD: 30.61,
      margin: 10,
      name: 'mocked-item',
      quantity: 1,
      rowWeight: 10,
      tariff: 135.76,
      tariffRate: 20,
      unitCost: 530,
      unitImportCost: 140,
      unitItemProfit: 121.32,
      unitLocalFleetCost: 10,
      unitOriginCosts: 772.1,
      unitPrice: 1213.18,
      unitTaxesFee: 169.76,
      unitWeight: 10,
      weightFraction: 1,
    },
  ],
};

export const _expectedMultiItemImportation: CalculateImportationResult = {
  pricesArray: [106.72, 913.65, 93.03, 799.4],
  articlesReport: [
    {
      CIF: 371.8,
      EXW: 53.5,
      FOB: 68.11,
      FODINFA: 1.86,
      ISD: 3.41,
      margin: 10,
      name: 'mocked-item-1',
      quantity: 5,
      rowWeight: 50,
      tariff: 74.36,
      tariffRate: 20,
      unitCost: 10,
      unitImportCost: 65.2,
      unitItemProfit: 10.67,
      unitLocalFleetCost: 0.65,
      unitOriginCosts: 14.28,
      unitPrice: 106.72,
      unitTaxesFee: 15.93,
      unitWeight: 10,
      weightFraction: 0.32468,
    },
    {
      CIF: 636.32,
      EXW: 567.1,
      FOB: 570.02,
      FODINFA: 3.18,
      ISD: 28.5,
      margin: 10,
      name: 'mocked-item-2',
      quantity: 1,
      rowWeight: 10,
      tariff: 127.26,
      tariffRate: 20,
      unitCost: 530,
      unitImportCost: 65.2,
      unitItemProfit: 91.37,
      unitLocalFleetCost: 0.65,
      unitOriginCosts: 597.5,
      unitPrice: 913.65,
      unitTaxesFee: 158.94,
      unitWeight: 10,
      weightFraction: 0.06494,
    },
    {
      CIF: 961.02,
      EXW: 385.2,
      FOB: 411.5,
      FODINFA: 4.81,
      ISD: 20.58,
      margin: 6,
      name: 'mocked-item-3',
      quantity: 12,
      rowWeight: 90,
      tariff: 0,
      tariffRate: 0,
      unitCost: 30,
      unitImportCost: 48.9,
      unitItemProfit: 5.58,
      unitLocalFleetCost: 0.49,
      unitOriginCosts: 35.94,
      unitPrice: 93.03,
      unitTaxesFee: 2.12,
      unitWeight: 7.5,
      weightFraction: 0.58442,
    },
    {
      CIF: 2316.5,
      EXW: 2268.4,
      FOB: 2269.57,
      FODINFA: 11.58,
      ISD: 113.48,
      margin: 10,
      name: 'mocked-item-4',
      quantity: 4,
      rowWeight: 4,
      tariff: 347.47,
      tariffRate: 15,
      unitCost: 530,
      unitImportCost: 6.52,
      unitItemProfit: 79.94,
      unitLocalFleetCost: 0.06,
      unitOriginCosts: 594.74,
      unitPrice: 799.4,
      unitTaxesFee: 118.13,
      unitWeight: 1,
      weightFraction: 0.02597,
    },
  ],
};

export const _expectedSelectedSingleItemImportation: CalculateImportationResult =
  {
    pricesArray: [0, 1213.18, 0, 0],
    articlesReport: [
      {
        CIF: 0,
        EXW: 0,
        FOB: 0,
        FODINFA: 0,
        ISD: 0,
        margin: 10,
        name: 'mocked-item-1',
        quantity: 100,
        rowWeight: 0,
        tariff: 0,
        tariffRate: 20,
        unitCost: 0,
        unitImportCost: 0,
        unitItemProfit: 0,
        unitLocalFleetCost: 0,
        unitOriginCosts: 0,
        unitPrice: 0,
        unitTaxesFee: 0,
        unitWeight: 10,
        weightFraction: 0,
      },
      {
        CIF: 678.82,
        EXW: 567.1,
        FOB: 612.1,
        FODINFA: 3.39,
        ISD: 30.61,
        margin: 10,
        name: 'mocked-item-2',
        quantity: 1,
        rowWeight: 10,
        tariff: 135.76,
        tariffRate: 20,
        unitCost: 530,
        unitImportCost: 140,
        unitItemProfit: 121.32,
        unitLocalFleetCost: 10,
        unitOriginCosts: 772.1,
        unitPrice: 1213.18,
        unitTaxesFee: 169.76,
        unitWeight: 10,
        weightFraction: 1,
      },
      {
        CIF: 0,
        EXW: 0,
        FOB: 0,
        FODINFA: 0,
        ISD: 0,
        margin: 6,
        name: 'mocked-item-3',
        quantity: 10,
        rowWeight: 0,
        tariff: 0,
        tariffRate: 0,
        unitCost: 30,
        unitImportCost: 0,
        unitItemProfit: 0,
        unitLocalFleetCost: 0,
        unitOriginCosts: 0,
        unitPrice: 0,
        unitTaxesFee: 0,
        unitWeight: 0,
        weightFraction: 0,
      },
      {
        CIF: 0,
        EXW: 0,
        FOB: 0,
        FODINFA: 0,
        ISD: 0,
        margin: 10,
        name: 'mocked-item-4',
        quantity: 0,
        rowWeight: 0,
        tariff: 0,
        tariffRate: 15,
        unitCost: 530,
        unitImportCost: 0,
        unitItemProfit: 0,
        unitLocalFleetCost: 0,
        unitOriginCosts: 0,
        unitPrice: 0,
        unitTaxesFee: 0,
        unitWeight: 1,
        weightFraction: 0,
      },
    ],
  };

export const _expectedMultiItemNoSettingsImportation: CalculateImportationResult =
  {
    pricesArray: [13.97, 740.27, 33.67, 710.53],
    articlesReport: [
      {
        CIF: 50.5,
        EXW: 50,
        FOB: 50,
        FODINFA: 0.25,
        ISD: 2.5,
        margin: 10,
        name: 'mocked-item-1',
        quantity: 5,
        rowWeight: 50,
        tariff: 10.1,
        tariffRate: 20,
        unitCost: 10,
        unitImportCost: 0,
        unitItemProfit: 1.4,
        unitLocalFleetCost: 0,
        unitOriginCosts: 10,
        unitPrice: 13.97,
        unitTaxesFee: 2.57,
        unitWeight: 10,
        weightFraction: 0.32468,
      },
      {
        CIF: 535.3,
        EXW: 530,
        FOB: 530,
        FODINFA: 2.68,
        ISD: 26.5,
        margin: 10,
        name: 'mocked-item-2',
        quantity: 1,
        rowWeight: 10,
        tariff: 107.06,
        tariffRate: 20,
        unitCost: 530,
        unitImportCost: 0,
        unitItemProfit: 74.03,
        unitLocalFleetCost: 0,
        unitOriginCosts: 530,
        unitPrice: 740.27,
        unitTaxesFee: 136.24,
        unitWeight: 10,
        weightFraction: 0.06494,
      },
      {
        CIF: 363.6,
        EXW: 360,
        FOB: 360,
        FODINFA: 1.82,
        ISD: 18,
        margin: 6,
        name: 'mocked-item-3',
        quantity: 12,
        rowWeight: 90,
        tariff: 0,
        tariffRate: 0,
        unitCost: 30,
        unitImportCost: 0,
        unitItemProfit: 2.02,
        unitLocalFleetCost: 0,
        unitOriginCosts: 30,
        unitPrice: 33.67,
        unitTaxesFee: 1.65,
        unitWeight: 7.5,
        weightFraction: 0.58442,
      },
      {
        CIF: 2141.2,
        EXW: 2120,
        FOB: 2120,
        FODINFA: 10.71,
        ISD: 106,
        margin: 10,
        name: 'mocked-item-4',
        quantity: 4,
        rowWeight: 4,
        tariff: 321.18,
        tariffRate: 15,
        unitCost: 530,
        unitImportCost: 0,
        unitItemProfit: 71.05,
        unitLocalFleetCost: 0,
        unitOriginCosts: 530,
        unitPrice: 710.53,
        unitTaxesFee: 109.47,
        unitWeight: 1,
        weightFraction: 0.02597,
      },
    ],
  };
