import { CalculateImportationResult } from '@src/types/importCalculator';

export const _expectedEmptySingleItemImportation: CalculateImportationResult = {
  pricesArray: [0],
  articlesReport: [
    {
      quantity: 1,
      unitWeight: 0,
      unitCost: 0,
      tariffRate: 0,
      margin: 0,
      unitPrice: 0,
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      tariff: 0,
      ISD: 0,
      name: 'mocked-item',
      rowWeight: 0,
      weightFraction: 0,
      unitOriginCosts: 0,
      unitTaxesFee: 0,
      unitImportCost: 0,
      unitLocalFleetCost: 0,
      unitItemProfit: 0,
    },
  ],
};

export const _expectedSingleItemImportation: CalculateImportationResult = {
  pricesArray: [1213.18],
  articlesReport: [
    {
      quantity: 1,
      unitWeight: 10,
      unitCost: 530,
      tariffRate: 20,
      margin: 10,
      unitPrice: 1213.18,
      CIF: 678.82,
      EXW: 567.1,
      FOB: 612.1,
      FODINFA: 3.39,
      tariff: 135.76,
      ISD: 30.61,
      name: 'mocked-item',
      rowWeight: 10,
      weightFraction: 1,
      unitOriginCosts: 772.1,
      unitTaxesFee: 169.76,
      unitImportCost: 140,
      unitLocalFleetCost: 10,
      unitItemProfit: 121.32,
    },
  ],
};

export const _expectedEmptyMultiItemImportation: CalculateImportationResult = {
  pricesArray: [0, 0, 0, 0],
  articlesReport: [
    {
      quantity: 1,
      unitWeight: 0,
      unitCost: 0,
      tariffRate: 0,
      margin: 0,
      unitPrice: 0,
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      tariff: 0,
      ISD: 0,
      name: 'mocked-item-1',
      rowWeight: 0,
      weightFraction: 0,
      unitOriginCosts: 0,
      unitTaxesFee: 0,
      unitImportCost: 0,
      unitLocalFleetCost: 0,
      unitItemProfit: 0,
    },
    {
      quantity: 1,
      unitWeight: 0,
      unitCost: 0,
      tariffRate: 0,
      margin: 0,
      unitPrice: 0,
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      tariff: 0,
      ISD: 0,
      name: 'mocked-item-2',
      rowWeight: 0,
      weightFraction: 0,
      unitOriginCosts: 0,
      unitTaxesFee: 0,
      unitImportCost: 0,
      unitLocalFleetCost: 0,
      unitItemProfit: 0,
    },
    {
      quantity: 1,
      unitWeight: 0,
      unitCost: 0,
      tariffRate: 0,
      margin: 0,
      unitPrice: 0,
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      tariff: 0,
      ISD: 0,
      name: 'mocked-item-3',
      rowWeight: 0,
      weightFraction: 0,
      unitOriginCosts: 0,
      unitTaxesFee: 0,
      unitImportCost: 0,
      unitLocalFleetCost: 0,
      unitItemProfit: 0,
    },
    {
      quantity: 1,
      unitWeight: 0,
      unitCost: 0,
      tariffRate: 0,
      margin: 0,
      unitPrice: 0,
      CIF: 0,
      EXW: 0,
      FOB: 0,
      FODINFA: 0,
      tariff: 0,
      ISD: 0,
      name: 'mocked-item-4',
      rowWeight: 0,
      weightFraction: 0,
      unitOriginCosts: 0,
      unitTaxesFee: 0,
      unitImportCost: 0,
      unitLocalFleetCost: 0,
      unitItemProfit: 0,
    },
  ],
};
